parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symblog
    database_user: symblog
    database_password: symblog
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b2bbc3441012f1133519cc766cd122888
    database_path: null
